config/routes.rb
Rails.application.routes.draw do
  resources :footbolists
  resources :wall_comments

  root 'welcome#index'

end

app/models/footbolist.rb
class Footbolist < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates_presence_of :image
  validates_presence_of :second_name
  validates_presence_of :name
end

app/models/wall_comment.rb
class WallComment < ActiveRecord::Base
validates_presence_of :title
validates_presence_of :message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/footbolists_controller.rb
class FootbolistsController < ApplicationController
  before_action :set_footbolist, only: [:show, :edit, :update, :destroy]

  # GET /footbolists
  # GET /footbolists.json
  def index
    @footbolists = Footbolist.all
  end

  # GET /footbolists/1
  # GET /footbolists/1.json
  def show
  end

  # GET /footbolists/new
  def new
    @footbolist = Footbolist.new
  end

  # GET /footbolists/1/edit
  def edit
  end

  # POST /footbolists
  # POST /footbolists.json
  def create
    @footbolist = Footbolist.new(footbolist_params)

    respond_to do |format|
      if @footbolist.save
        format.html { redirect_to @footbolist, notice: 'Footbolist was successfully created.' }
        format.json { render :show, status: :created, location: @footbolist }
      else
        format.html { render :new,notice: 'Pustie polya, bratan.'}
        format.json { render json: @footbolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /footbolists/1
  # PATCH/PUT /footbolists/1.json
  def update
    respond_to do |format|
      if @footbolist.update(footbolist_params)
        format.html { redirect_to @footbolist, notice: 'Footbolist was successfully updated.' }
        format.json { render :show, status: :ok, location: @footbolist }
      else
        format.html { render :edit,notice: 'Pustie polya, bratan.'}
        format.json { render json: @footbolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /footbolists/1
  # DELETE /footbolists/1.json
  def destroy
    @footbolist.destroy
    respond_to do |format|
      format.html { redirect_to footbolists_url, notice: 'Footbolist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_footbolist
      @footbolist = Footbolist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def footbolist_params
      params.require(:footbolist).permit(:name, :second_name, :description, :club, :image)
    end
end

app/controllers/wall_comments_controller.rb
class WallCommentsController < ApplicationController
  def index

  end

  def new

  end

  def create
    @comment = WallComment.create(wall_comment_params)
    respond_to do |format|
      format.html { redirect_to :root, notice: 'Comment was successfully created.' }
      CommentsMailer.welcome_email(wall_comment_params[:title]).deliver_later
    end
  end

  private

  def wall_comment_params
    params.require(:wall_comment).permit(:title, :message)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @photos_info = Footbolist.all.map{|f| {name: "#{f.name} #{f.second_name}", url:f.image.url}}
    @comments = WallComment.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/footbolists_helper.rb
module FootbolistsHelper
end

app/views/footbolists/_form.html.erb
<%= form_for(@footbolist) do |f| %>
  <% if @footbolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@footbolist.errors.count, "error") %> prohibited this footbolist from being saved:</h2>

      <ul>
      <% @footbolist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, pattern: '[А-ЯЁ][а-яё\s]{1,30}' %>  </div>
  <div class="field">
    <%= f.label :second_name %><br>
    <%= f.text_field :second_name, pattern: '[А-ЯЁ][а-яё\s]{1,30}' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :club %><br>
    <%= f.text_field :club %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/footbolists/edit.html.erb
<div class="parents_block">
  <h1>Editing Footbolist</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @footbolist %> |
  <%= link_to 'Back', footbolists_path %>

</div>

app/views/footbolists/index.html.erb
<div class='fon'>
  <div class='header'>
      <h1><center>Footbal Players DB</center></h1>
        <div class='btn-group fon'>
          <%= link_to "Home Page", root_path, class: 'btn btn-default col-md-6'%>
          <%= link_to 'New Footbolist', new_footbolist_path, class: 'btn btn-default col-md-offset-6 col-md-6' %>
        </div>
  </div>

  <div class="fon post_header">
    <p id="notice"><%= notice %></p>
    <table class="main_table col-md-12">
      <thead>
        <tr class="row">
          <th class="col-md-3">Image</th>
          <th class="col-md-3">Name</th>
          <th class="col-md-3">Second name</th>
          <th class="col-md-3" colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @footbolists.each do |footbolist| %>
            <tr class="row">
                <td class="col-md-2"><%= image_tag footbolist.image.url, height: '60', width: '60' %></td>

                <td class="col-md-3"><%= footbolist.name %></td>

                <td class="col-md-3"><%= footbolist.second_name %></td>


                <td class="col-md-4">
                  <div class='btn-group'>  <%= link_to 'Show', footbolist, class: 'btn btn-default' %>
                    <%= link_to 'Edit', edit_footbolist_path(footbolist), class: 'btn btn-default' %>
                    <%= link_to 'Destroy', footbolist, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
                  </div>
                </td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/footbolists/new.html.erb
<div class="parents_block">
  <h1>New Footbolist</h1>

  <%= render 'form' %>

  <%= link_to 'Back', footbolists_path %>

</div>

app/views/footbolists/show.html.erb
<div class="parents_block">
  <p id="notice"><%= notice %></p>
  <p>
    <%= image_tag @footbolist.image.url, height: '120', width: '120' %>
  </p>


  <p>
    <strong>Name:</strong>
    <%= @footbolist.name %>
  </p>

  <p>
    <strong>Second name:</strong>
    <%= @footbolist.second_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @footbolist.description %>
  </p>

  <p>
    <strong>Club:</strong>
    <%= @footbolist.club %>
  </p>

  <%= link_to 'Edit', edit_footbolist_path(@footbolist) %> |
  <%= link_to 'Back', footbolists_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mokali</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="fon">
  <div class='header'>
      <h1><center>Footbal Players DB</center></h1>
        <%= link_to "Show all Footbolist", footbolists_path, class: 'btn btn-default btn-block'%>
  </div>


</div>
<div class="parents_block row post_header">
    <!-- Wrapper for slides -->
      <%if @photos_info.size < 1%>
        <p>no photos</p>
      <%else%>
      <div id="carousel-example-generic" class="carousel slide col-md-offset-1 col-md-6 " data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="active item">
            <%= image_tag @photos_info.first[:url], class: 'displayed object-fit_contain item_img col-md-12'%>
            <div class="carousel-caption">
              <%= @photos_info.first[:name] %>
            </div>
          </div>
          <% @photos_info.drop(1).each do |item| %>
              <div class="item">
                <%= image_tag item[:url], class: 'object-fit_contain item_img col-md-12' %>
                <div class="carousel-caption">
                  <%= item[:name] %>
                </div>
              </div>
          <% end %>
          <a class="left carousel-control " href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <%end%>
    </div>

    <!-- Controls -->

    <p id="notice"><%= notice %></p>

  <div id="comment_wall" class='col-md-offset-1 col-md-3'>
    <div class=' col-md-offset-2 col-md-8'>
      <%= form_for WallComment.new, remote: true do |f|%>
        <div class="field ">
          <%= f.text_field :title,placeholder:'Nickname...',class:'title' %>
        </div>
        <div class="field ">
          <%= f.text_field :message,placeholder:'Message...',class:'message' %>
        </div>
        <%= f.submit  %>
      <% end %>
    </div>
    <div class="fon">
      <div class="comments">
        <% @comments.each do |comment| %>
          <p>
            <b>Пользователь:</b> <%= comment.title %>
          </p>
          <p>
            <b>Сообщение:</b>    <%= comment.message %>
          </p>
          <hr>
        <% end %>
      </div>
    </div>
  </div>

</div>